include(ExternalProject)
include(GNUInstallDirs)

ExternalProject_Add(
  BlancPlugins
  SOURCE_DIR "${CMAKE_SOURCE_DIR}/plugins"
  BINARY_DIR "${CMAKE_BINARY_DIR}/plugins"
  CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}/bin -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT=$ENV{BOOST_ROOT}
  UPDATE_COMMAND ""
  PATCH_COMMAND  ""
  TEST_COMMAND   ""
  INSTALL_COMMAND ""
  BUILD_ALWAYS 1
)
