message(STATUS "Setting up Eosio Wasm Toolchain")
set(CMAKE_SYSTEM_NAME WebAssembly)

if (WASM_ROOT STREQUAL "")
   set(WASM_INSTALL_ROOT "${CMAKE_INSTALL_PREFIX}")
else(WASM_ROOT STREQUAL "")
   set(WASM_INSTALL_ROOT "${WASM_ROOT}")
endif(WASM_ROOT STREQUAL "")

set(CMAKE_C_COMPILER "${WASM_INSTALL_ROOT}/bin/eosio.cc")
set(CMAKE_CXX_COMPILER "${WASM_INSTALL_ROOT}/bin/eosio.cpp")

set(CMAKE_C_FLAGS " -O3 ")
set(CMAKE_CXX_FLAGS " -O3 ")

set(WASM_LINKER "${WASM_INSTALL_ROOT}/bin/eosio.ld")

set(CMAKE_C_LINK_EXECUTABLE "${WASM_LINKER} <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")
set(CMAKE_CXX_LINK_EXECUTABLE "${WASM_LINKER} <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>")

set(CMAKE_AR "${WASM_INSTALL_ROOT}/bin/eosio-ar" CACHE PATH "ar" FORCE)
set(CMAKE_RANLIB "${WASM_INSTALL_ROOT}/bin/eosio-ranlib" CACHE PATH "ranlib" FORCE)

set(EosioLib_DIR ${WASM_INSTALL_ROOT}/lib/cmake)

# hack for CMake on Linux
set(CMAKE_SHARED_LIBRARY_LINK_C_FLAGS)
set(CMAKE_SHARED_LIBRARY_LINK_CXX_FLAGS)
# hack for OSX
set(CMAKE_OSX_SYSROOT="${WASM_INSTALL_ROOT}/eosio.wasmsdk")
set(CMAKE_OSX_DEPLOYMENT_TARGET="")
