if (NOT EOSIO_WASM_OLD_BEHAVIOR STREQUAL "On")

  macro(add_contract CONTRACT_NAME TARGET)
    add_executable( ${TARGET} ${ARGN} )
    target_link_libraries(${TARGET} PRIVATE eosio_dsm)
    target_compile_options( ${TARGET} PRIVATE -contract ${CONTRACT_NAME} )
  endmacro()
  macro (target_ricardian_directory TARGET DIR)
    target_compile_options( ${TARGET} PUBLIC -R${DIR} )
    file(GLOB contracts ${DIR}/*.contracts.md ${DIR}/*.clauses.md)
    add_custom_target(${TARGET}.ricardian DEPENDS ${contracts})
    add_dependencies( ${TARGET} ${TARGET}.ricardian )
  endmacro()

else()

  macro(add_contract CONTRACT_NAME TARGET)
    add_executable( ${TARGET}.wasm ${ARGN} )
    set_target_properties(${TARGET}.wasm PROPERTIES SUFFIX "")
    target_compile_options( ${TARGET}.wasm PRIVATE -contract ${CONTRACT_NAME} )
    target_link_libraries(${TARGET}.wasm PRIVATE eosio_dsm)
  endmacro()
  macro (target_ricardian_directory TARGET DIR)
    target_compile_options( ${TARGET}.wasm PUBLIC -R${DIR} )
    file(GLOB contracts ${DIR}/*.contracts.md ${DIR}/*.clauses.md)
    add_custom_target(${TARGET}.ricardian DEPENDS ${contracts})
    add_dependencies( ${TARGET} ${TARGET}.ricardian )
  endmacro()

endif()
