include(ExternalProject)
include(GNUInstallDirs)

ExternalProject_Add(
  BlancTools
  CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=Release -DVERSION_FULL=${VERSION_FULL} -DCMAKE_INSTALL_BINDIR=${CMAKE_INSTALL_BINDIR} -DVERSION_MAJOR=${VERSION_MAJOR} -DVERSION_MINOR=${VERSION_MINOR} -DVERSION_PATCH=${VERSION_PATCH} -DBOOST_ROOT=$ENV{BOOST_ROOT}

  SOURCE_DIR "${CMAKE_SOURCE_DIR}/tools"
  BINARY_DIR "${CMAKE_BINARY_DIR}/tools"
  UPDATE_COMMAND ""
  PATCH_COMMAND  ""
  TEST_COMMAND   ""
  INSTALL_COMMAND ""
  BUILD_ALWAYS 1
)

ExternalProject_Add(
  toolchain-tester
  SOURCE_DIR "${CMAKE_SOURCE_DIR}/tools/toolchain-tester"
  BINARY_DIR "${CMAKE_BINARY_DIR}/tools/toolchain-tester"
  UPDATE_COMMAND ""
  PATCH_COMMAND  ""
  TEST_COMMAND   ""
  INSTALL_COMMAND ""
  BUILD_ALWAYS 1
)
