language: cpp
git:
  depth: false
if: fork = true OR type = api OR type = cron
matrix:
  include:
  - os: linux
    dist: xenial
    services: docker
    env:
    - IMAGE_TAG='ubuntu-18.04'
  - os: linux
    dist: xenial
    services: docker
    env:
    - IMAGE_TAG='ubuntu-16.04'
  - os: linux
    dist: xenial
    services: docker
    env:
    - IMAGE_TAG='amazonlinux-2'
  - os: linux
    dist: xenial
    services: docker
    env:
    - IMAGE_TAG='centos-7.6'
  - os: osx
    osx_image: xcode10.2
    addons:
      homebrew:
        update: true
        packages:
        - automake
        - libtool
        - wget
        - cmake
        - gmp
        - gettext
        - doxygen
        - graphviz
        - lcov
        - python@3
script: "./.cicd/build.sh && ./.cicd/tests.sh"
