language: cpp
git:
  depth: false
cache:
  ccache: true
  directories:
  - "$HOME/Library/Caches/Homebrew"
matrix:
  include:
  - os: linux
    dist: xenial
    services: docker
    env:
    - IMAGE_TAG='ubuntu-18.04'
  - os: linux
    dist: xenial
    services: docker
    env:
    - IMAGE_TAG='ubuntu-16.04'
  - os: linux
    dist: xenial
    services: docker
    env:
    - IMAGE_TAG='amazonlinux-2'
  - os: linux
    dist: xenial
    services: docker
    env:
    - IMAGE_TAG='centos-7'
  - os: osx
    osx_image: xcode10.2
    addons:
      homebrew:
        update: true
        packages:
        - automake
        - libtool
        - wget
        - cmake
        - gmp
        - gettext
        - doxygen
        - graphviz
        - lcov
        - python@3
        - ccache
    env:
    - PATH="/usr/local/opt/ccache/libexec:$PATH"
script: "./.cicd/travis-build.sh\n"
notifications:
  webhooks:
    secure: aJn9fpJdjKR7XWqE9fD9+v5WNgpzaavHP5S3G0EK8zkfc5GoUTsd0m9DGkAasl/vYaiuTScAHtGh3Ve+bXynjbgpGIY+OwIGC4hw63HlF4Ro5tV+4cQ18kyhJZB4Hd2FxVYYXw8gEGfdGLqdNeqNoD0jlbZUFN4MIVyXIhpr8Suc0Jujp/4W/OcrWh+lsaGvundUgd3FGt3iGEg++RGn2T6LFreN+dcF1/m0HzVLl0gVlqH3nUn3WmRU5At+H+HHGxutzFfwk8ogUdeID1MHk4hjq6AM8h6b6J/kOYknB54l+661G6eJOXqSUowu+RLC3PknrJUH/XTR6WZ1NtrOMURSfATKBozDRLBAWUn716othIOnLKywOhcNzsYNzMdVSeL4Ln8ZXG0m0yYz4M98T6dV8YJJg3L0g1yYHknzwZnD6N6TCbYjOz/go0iQEvP10K3prygBZCDBJHER5KXZTycZygGB8zkkwEJvfPm51F9UgTCTiatpKfrqWz/3u0Llr3QMELDYXAkbSSehAqsrk7cuzoE6qwc6H/eQiQ/gvRupS0iQN+C2UZDc8SeBEp/pkHrpnHVFJ+O9Ezv/0y4peqxIevDA3jEdv1N3CTC2bq9ZepCPAJ2qJ5ULUDLDH4KnSlTzCE3xY/YSFgrUmLFC8BLpKR8/xzCXISWBoOAgLbs=
env:
  global:
    secure: R7FJdq6uHGvzI20BQs9zSdU1T+CcplRw4+XeEgQgOtPQTe5lgdVKKIZa5UJzYPUJog5/G11dzlBm+Wb8ToSnp7ghgep2WATJux7yvloNdvFzSca8R7+RfmMbAVqAw+7lDqlwPYy8wWZLms06BqZrWl6aEGdY3gx9CoPbhUfPNjBn2lMwnc5ZxE0H4cbi/ayvmvdbShZzb0MOfUNSQNUumU2r1h4ARg4bj57+FhRL/XjcYmbVgPbweKrcxyiGzmwfSvOqzKM/9jPjPotdsqpROADw/CuQGrc972pSRSwb5dH4z4qlwaFbJPTHk45PmrqJP6ypwiMostwCpRGKL5rj+99ghZoK/+e3DAVPpJyxL5yoRmgBd2wuK9jC5xNVgCUjWPxDHUyCyY+b3B2RFUOqdrJjBxoMmJtpeLIFcBV4Ft5ke2bX1HGttIa9VEF8WlenAwS0Gy/cB6tRb2TZdhBGsIKFnZeLCOSL04AirV47icIVKfCcuk+qkpZj9hJExqPk6KjlndxOUBHpa6e5yHMFpy9I8D8RGLX1MNH3IYk1+VNBn09I7Bv7vVF5JsVai9Jv1K6OT9A4ZP7DNra0RefzOZup/QAArhPZkY04T3v4B3TE9l/AnNdUwfHyAqjEPy95vuEqbMqSBEeDnaDVGTgQJioXHTiYyUBMWaNpFvQ51/E=
