language: cpp
git:
  depth: false
# cache:
#   ccache: true
#   directories:
#   - "$HOME/Library/Caches/Homebrew"
matrix:
  include:
  - os: linux
    dist: xenial
    services: docker
    env:
    - IMAGE_TAG='ubuntu-18.04'
    - MAKE_PROC_LIMIT='2'
  - os: linux
    dist: xenial
    services: docker
    env:
    - IMAGE_TAG='ubuntu-16.04'
    - MAKE_PROC_LIMIT='2'
  - os: linux
    dist: xenial
    services: docker
    env:
    - IMAGE_TAG='amazonlinux-2'
    - MAKE_PROC_LIMIT='2'
  - os: linux
    dist: xenial
    services: docker
    env:
    - IMAGE_TAG='centos-7'
    - MAKE_PROC_LIMIT='2'
  - os: osx
    osx_image: xcode10.2
    addons:
      homebrew:
        update: true
        packages:
        - automake
        - libtool
        - wget
        - cmake
        - gmp
        - gettext
        - doxygen
        - graphviz
        - lcov
        - python@3
        # - ccache
    env:
      - MAKE_PROC_LIMIT='2'
      # - PATH="/usr/local/opt/ccache/libexec:$PATH"
script:
  - "export -f travis_wait"
  - "export -f travis_jigger"
  - "./.cicd/travis-build.sh"
