env:
  BUILD_TIMEOUT: 120
  TEST_TIMEOUT: 60
  TIMEOUT: 120
  VERBOSE: true

steps:

  - trigger: "eosio-dot-cdt-base-images-beta"
    label: ":docker: Ensure base images exist"
    build:
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"

  - wait

  - label: ":aws: [Amazon] 2 Build"
    command:
      - "mkdir /workdir/build && cd /workdir/build && cmake /workdir && make -j $(getconf _NPROCESSORS_ONLN)"
      - "cd /workdir/build && ctest -j$(getconf _NPROCESSORS_ONLN) -L unit_tests -V -T Test"
    agents:
      queue: "automation-eos-builder-fleet"
    plugins:
      - docker#v3.2.0:
          shell: ["/bin/bash", "-i", "-e", "-c"]
          debug: $DEBUG
          image: "eosio/producer:eosio.cdt-amazonlinux-2-69bd00ad0031c2a87f4cd710d79e037f609ceb2a"
    timeout: $BUILD_TIMEOUT
    skip: $SKIP_AMAZON_LINUX_2

  - label: ":centos: [CentOS] 7 Build"
    command:
      - "mkdir /workdir/build && cd /workdir/build && source /opt/rh/devtoolset-7/enable && source /opt/rh/python33/enable && cmake /workdir && make -j $(getconf _NPROCESSORS_ONLN)"
      - "cd /workdir/build && ctest -j$(getconf _NPROCESSORS_ONLN) -L unit_tests -V -T Test"
    agents:
      queue: "automation-eos-builder-fleet"
    plugins:
      - docker#v3.2.0:
          shell: ["/bin/bash", "-i", "-e", "-c"]
          debug: $DEBUG
          image: "eosio/producer:eosio.cdt-centos-7-858b7356721b0c40a5080994c512434827f88d24"
    timeout: $BUILD_TIMEOUT
    skip: $SKIP_CENTOS_7

  - label: ":ubuntu: [Ubuntu] 16.04 Build"
    command:
      - "mkdir /workdir/build && cd /workdir/build && cmake /workdir && make -j $(getconf _NPROCESSORS_ONLN)"
      - "cd /workdir/build && ctest -j$(getconf _NPROCESSORS_ONLN) -L unit_tests -V -T Test"
    agents:
      queue: "automation-eos-builder-fleet"
    plugins:
      - docker#v3.2.0:
          shell: ["/bin/bash", "-i", "-e", "-c"]
          debug: $DEBUG
          image: "eosio/producer:eosio.cdt-ubuntu-16.04-0d4dbbff7f87bf4bd9a421d23603e0e9cbb1b32f"
    timeout: $BUILD_TIMEOUT
    skip: $SKIP_UBUNTU_16

  - label: ":ubuntu: [Ubuntu] 18.04 Build"
    command:
      - "mkdir /workdir/build && cd /workdir/build && cmake /workdir && make -j $(getconf _NPROCESSORS_ONLN)"
      - "cd /workdir/build && ctest -j$(getconf _NPROCESSORS_ONLN) -L unit_tests -V -T Test"
    agents:
      queue: "automation-eos-builder-fleet"
    plugins:
      - docker#v3.2.0:
          shell: ["/bin/bash", "-i", "-e", "-c"]
          debug: $DEBUG
          image: "eosio/producer:eosio.cdt-ubuntu-18.04-f3da3cea9e58d97e320fb6e96617181944117521"
    timeout: $BUILD_TIMEOUT
    skip: $SKIP_UBUNTU_18

  - label: ":darwin: [Darwin] 10.14 Build"
    command:
      - "brew install git automake libtool wget cmake gmp gettext doxygen graphviz lcov python@3"
      - "git clone $BUILDKITE_REPO eosio.cdt && cd eosio.cdt && git checkout $BUILDKITE_COMMIT && git submodule update --init --recursive"
      - "cd eosio.cdt && mkdir build && cd build && cmake .. && make -j$(getconf _NPROCESSORS_ONLN)"
      - "cd eosio.cdt/build && ctest -j$(getconf _NPROCESSORS_ONLN) -L unit_tests -V -T Test"
    plugins:
      - chef/anka#v0.5.1:
          no-volume: true
          inherit-environment-vars: true
          vm-name: 10.14.4_6C_14G_40G
          vm-registry-tag: "clean::cicd::git-ssh::nas::brew"
          modify-cpu: 12
          modify-ram: 24
          always-pull: true
          debug: true
          wait-network: true
    agents:
      - "queue=mac-anka-large-node-fleet"
    timeout: $BUILD_TIMEOUT
    skip: $SKIP_MOJAVE