steps:

  - wait

  - label: ":aws: Amazon_Linux 2 - Build"
    command:
      - "./.cicd/build.sh"
      - "tar -pczf build.tar.gz build && buildkite-agent artifact upload build.tar.gz"
    env:
      IMAGE_TAG: "amazonlinux-2"
    agents:
      queue: "automation-eos-builder-fleet"
    timeout: ${TIMEOUT:-10}
    skip: $SKIP_AMAZON_LINUX_2

  - label: ":centos: CentOS 7.6 - Build"
    command:
      - "./.cicd/build.sh"
      - "tar -pczf build.tar.gz build && buildkite-agent artifact upload build.tar.gz"
    env: 
      IMAGE_TAG: "centos-7.6"
    agents:
      queue: "automation-eos-builder-fleet"
    timeout: ${TIMEOUT:-10}
    skip: $SKIP_CENTOS_7

  - label: ":ubuntu: Ubuntu 16.04 - Build"
    command:
      - "./.cicd/build.sh"
      - "tar -pczf build.tar.gz build && buildkite-agent artifact upload build.tar.gz"
    env: 
      IMAGE_TAG: "ubuntu-16.04"
    agents:
      queue: "automation-eos-builder-fleet"
    timeout: ${TIMEOUT:-10}
    skip: $SKIP_UBUNTU_16

  - label: ":ubuntu: Ubuntu 18.04 - Build"
    command:
      - "./.cicd/build.sh"
      - "tar -pczf build.tar.gz build && buildkite-agent artifact upload build.tar.gz"
    env:
      IMAGE_TAG: "ubuntu-18.04"
    agents:
      queue: "automation-eos-builder-fleet"
    timeout: ${TIMEOUT:-10}
    skip: $SKIP_UBUNTU_18

  - label: ":darwin: macOS 10.14 - Build"
    command:
      - "brew install git automake libtool wget cmake gmp gettext doxygen graphviz lcov python@3"
      - "git clone $BUILDKITE_REPO eosio.cdt && cd eosio.cdt && git checkout $BUILDKITE_COMMIT && git submodule update --init --recursive"
      - "cd eosio.cdt && ./.cicd/build.sh"
      - "cd eosio.cdt && tar -pczf build.tar.gz build && buildkite-agent artifact upload build.tar.gz"
    plugins:
      - chef/anka#v0.5.1:
          no-volume: true
          inherit-environment-vars: true
          vm-name: 10.14.4_6C_14G_40G
          vm-registry-tag: "clean::cicd::git-ssh::nas::brew::buildkite-agent"
          modify-cpu: 12
          modify-ram: 24
          always-pull: true
          debug: true
          wait-network: true
    agents:
      - "queue=mac-anka-large-node-fleet"
    skip: $SKIP_MOJAVE

  - wait

  - label: ":aws: Amazon_Linux 2 - Unit Tests"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':aws: Amazon_Linux 2 - Build' --agent-access-token $$BUILDKITE_AGENT_ACCESS_TOKEN && tar -xzf build.tar.gz"
      - "./.cicd/tests.sh"
    env:
      IMAGE_TAG: "amazonlinux-2"
    agents:
      queue: "automation-eos-builder-fleet"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_AMAZON_LINUX_2}${SKIP_UNIT_TESTS}

  - label: ":centos: CentOS 7.6 - Unit Tests"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':centos: CentOS 7.6 - Build' --agent-access-token $$BUILDKITE_AGENT_ACCESS_TOKEN && tar -xzf build.tar.gz"
      - "./.cicd/tests.sh"
    env: 
      IMAGE_TAG: "centos-7.6"
    agents:
      queue: "automation-eos-builder-fleet"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_CENTOS_7}${SKIP_UNIT_TESTS}

  - label: ":ubuntu: Ubuntu 16.04 - Unit Tests"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':ubuntu: Ubuntu 16.04 - Build' --agent-access-token $$BUILDKITE_AGENT_ACCESS_TOKEN && tar -xzf build.tar.gz"
      - "./.cicd/tests.sh"
    env: 
      IMAGE_TAG: "ubuntu-16.04"
    agents:
      queue: "automation-eos-builder-fleet"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_UBUNTU_16}${SKIP_UNIT_TESTS}

  - label: ":ubuntu: Ubuntu 18.04 - Unit Tests"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':ubuntu: Ubuntu 18.04 - Build' --agent-access-token $$BUILDKITE_AGENT_ACCESS_TOKEN && tar -xzf build.tar.gz"
      - "./.cicd/tests.sh"
    env:
      IMAGE_TAG: "ubuntu-18.04"
    agents:
      queue: "automation-eos-builder-fleet"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_UBUNTU_18}${SKIP_UNIT_TESTS}

  - label: ":darwin: macOS 10.14 - Unit Tests"
    command:
      - "brew install git automake libtool wget cmake gmp gettext doxygen graphviz lcov python@3"
      - "git clone $BUILDKITE_REPO eosio.cdt && cd eosio.cdt && git checkout $BUILDKITE_COMMIT && git submodule update --init --recursive"
      - "cd eosio.cdt && buildkite-agent artifact download build.tar.gz . --step ':darwin: macOS 10.14 - Build' && tar -xzf build.tar.gz"
      - "cd eosio.cdt && ./.cicd/tests.sh"
    plugins:
      - chef/anka#v0.5.1:
          no-volume: true
          inherit-environment-vars: true
          vm-name: 10.14.4_6C_14G_40G
          vm-registry-tag: "clean::cicd::git-ssh::nas::brew::buildkite-agent"
          modify-cpu: 12
          modify-ram: 24
          always-pull: true
          debug: true
          wait-network: true
    agents:
      - "queue=mac-anka-large-node-fleet"
    skip: ${SKIP_MOJAVE}${SKIP_UNIT_TESTS}

  - wait:
    continue_on_failure: true

  - label: ":bar_chart: Unit Tests Metrics"
    command: |
      echo '+++ :compression: Extracting Unit Tests Metrics Code'
      tar -zxf .cicd/metrics/test-metrics.tar.gz
      echo '+++ :javascript: Running test-metrics.js'
      node --max-old-space-size=32768 test-metrics.js
    agents:
      queue: "automation-eos-builder-fleet"
    timeout: 10
    soft_fail: true

  - wait

  - label: ":centos: Centos 7.6 - Package Builder"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':centos: CentOS 7.6 - Build' --agent-access-token $$BUILDKITE_AGENT_ACCESS_TOKEN && tar -xzf build.tar.gz"
      - "./.cicd/package.sh"
    env:
      BUILDKITE_AGENT_ACCESS_TOKEN:
      IMAGE_TAG: "centos-7.6"
      OS: "centos" # OS and PKGTYPE required for lambdas
      PKGTYPE: "rpm"
    agents:
      queue: "automation-eos-builder-fleet"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_CENTOS_7}${SKIP_PACKAGE_BUILDER}

  - label: ":ubuntu: Ubuntu 18.04 - Package Builder"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':ubuntu: Ubuntu 18.04 - Build' --agent-access-token $$BUILDKITE_AGENT_ACCESS_TOKEN && tar -xzf build.tar.gz"
      - "./.cicd/package.sh"
    env:
      BUILDKITE_AGENT_ACCESS_TOKEN:
      IMAGE_TAG: "ubuntu-18.04"
      OS: "ubuntu-18.04" # OS and PKGTYPE required for lambdas
      PKGTYPE: "deb"
    agents:
      queue: "automation-eos-builder-fleet"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_UBUNTU_18}${SKIP_PACKAGE_BUILDER}

  - label: ":darwin: Mojave - Package Builder"
    command:
      - "git clone $BUILDKITE_REPO eosio.cdt && cd eosio.cdt && git checkout $BUILDKITE_COMMIT"
      - "cd eosio.cdt && buildkite-agent artifact download build.tar.gz . --step ':darwin: macOS 10.14 - Build' && tar -xzf build.tar.gz"
      - "cd eosio.cdt && ./.cicd/package.sh"
    plugins:
      - chef/anka#v0.5.1:
          no-volume: true
          inherit-environment-vars: true
          vm-name: 10.14.4_6C_14G_40G
          vm-registry-tag: "clean::cicd::git-ssh::nas::brew::buildkite-agent"
          always-pull: true
          debug: true
          wait-network: true
    agents:
      - "queue=mac-anka-node-fleet"
    timeout: 10
    skip: ${SKIP_MOJAVE}${SKIP_PACKAGE_BUILDER}

  - label: ":git: Git Submodule Regression Check"
    command:
      - "./.cicd/submodule-regression-checker.sh"
    agents:
      queue: "automation-basic-builder-fleet"
    timeout: 5