env:
  OUR_PR_REPO: "git@github.com:b1-as/taurus-cdt.git"
  SKIP_LINUX: "true"
steps:
  - wait

  - label: ":aws: Amazon_Linux 2 - Build"
    command:
      - "./.cicd/build.sh"
      - "tar -pczf build.tar.gz build && buildkite-agent artifact upload build.tar.gz"
    env:
      IMAGE_TAG: "amazonlinux-2"
    agents:
      queue: "automation-gke-ha-dev-taurus-builder-fleet"
    timeout: ${TIMEOUT:-60}
    skip: ${SKIP_AMAZON_LINUX_2}${SKIP_LINUX}

  - label: ":centos: CentOS 7.7 - Build"
    command:
      - "./.cicd/build.sh"
      - "tar -pczf build.tar.gz build && buildkite-agent artifact upload build.tar.gz"
    env: 
      IMAGE_TAG: "centos-7.7"
    agents:
      queue: "automation-gke-ha-dev-taurus-builder-fleet"
    timeout: ${TIMEOUT:-60}
    skip: ${SKIP_CENTOS_7}${SKIP_LINUX}

  - label: ":ubuntu: Ubuntu 18.04 - Build"
    command:
      - "./.cicd/build.sh"
      - "tar -pczf build.tar.gz build && buildkite-agent artifact upload build.tar.gz"
    env:
      IMAGE_TAG: "ubuntu-18.04"
    agents:
      queue: "automation-gke-ha-dev-taurus-builder-fleet"
    timeout: ${TIMEOUT:-60}
    skip: ${SKIP_UBUNTU_18}${SKIP_LINUX}

  - label: ":ubuntu: Ubuntu 20.04 - Build"
    command:
      - "./.cicd/build.sh"
      - "tar -pczf build.tar.gz build && buildkite-agent artifact upload build.tar.gz"
    env:
      IMAGE_TAG: "ubuntu-20.04"
    agents:
      queue: "automation-gke-ha-dev-taurus-builder-fleet"
    timeout: ${TIMEOUT:-60}
    skip: ${SKIP_UBUNTU_20}${SKIP_LINUX}

  - label: ":darwin: macOS 10.15 - Build"
    command:
      - "git clone ${OUR_PR_REPO} taurus-cdt"
      - "cd taurus-cdt && if [[ $BUILDKITE_BRANCH =~ ^pull/[0-9]+/head: ]]; then git fetch -v --prune origin refs/pull/$(echo $BUILDKITE_BRANCH | cut -d/ -f2)/head; fi"
      - "cd taurus-cdt && git checkout -f $BUILDKITE_COMMIT && git submodule update --init --recursive"
      - "cd taurus-cdt && ./.cicd/build.sh"
      - "cd taurus-cdt && tar -pczf build.tar.gz build && buildkite-agent artifact upload build.tar.gz"
    plugins:
      - EOSIO/anka#v0.6.0:
          no-volume: true
          inherit-environment-vars: true
          vm-name: 10.15.5_6C_14G_80G
          vm-registry-tag: "clean::cicd::git-ssh::nas::brew::buildkite-agent::${MACOS_10_15_TAG}"
          modify-cpu: 12
          modify-ram: 24
          always-pull: true
          debug: true
          wait-network: true
          pre-execute-sleep: 5
          pre-execute-ping-sleep: github.com
          failover-registries:
            - 'registry-1'
            - 'registry-2'
          pre-commands:
            - "rm -rf mac-anka-fleet; git clone git@github.com:EOSIO/mac-anka-fleet.git && cd mac-anka-fleet && . ./ensure-tag.bash -u 12 -r 25G -a '-n'"
      - EOSIO/skip-checkout#v0.1.1:
          cd: ~
    env:
      PROJECT_TAG: ${MACOS_10_15_TAG}
      REPO: ${OUR_PR_REPO}
      REPO_COMMIT: $BUILDKITE_COMMIT
      TAG_COMMANDS: "git clone ${OUR_PR_REPO} taurus-cdt && cd taurus-cdt && git checkout -f $BUILDKITE_COMMIT && git submodule update --init --recursive && . ./.cicd/platforms/macos-10.15.sh && cd ~/taurus-cdt && cd .. && rm -rf taurus-cdt"
      TEMPLATE: 10.15.5_6C_14G_80G
      TEMPLATE_TAG: clean::cicd::git-ssh::nas::brew::buildkite-agent
    timeout: ${TIMEOUT:-120}
    agents:
      - "queue=mac-anka-large-node-fleet"
    skip: ${SKIP_MACOS_10_15}${SKIP_MAC}

  - wait

  - label: ":aws: Amazon_Linux 2 - Unit Tests"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':aws: Amazon_Linux 2 - Build' --agent-access-token $$BUILDKITE_AGENT_ACCESS_TOKEN && tar -xzf build.tar.gz"
      - "./.cicd/tests.sh"
    env:
      IMAGE_TAG: "amazonlinux-2"
    agents:
      queue: "automation-gke-ha-dev-taurus-tester-fleet"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_AMAZON_LINUX_2}${SKIP_LINUX}${SKIP_UNIT_TESTS}

  - label: ":centos: CentOS 7.7 - Unit Tests"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':centos: CentOS 7.7 - Build' --agent-access-token $$BUILDKITE_AGENT_ACCESS_TOKEN && tar -xzf build.tar.gz"
      - "./.cicd/tests.sh"
    env: 
      IMAGE_TAG: "centos-7.7"
    agents:
      queue: "automation-gke-ha-dev-taurus-tester-fleet"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_CENTOS_7}${SKIP_LINUX}${SKIP_UNIT_TESTS}

  - label: ":ubuntu: Ubuntu 18.04 - Unit Tests"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':ubuntu: Ubuntu 18.04 - Build' --agent-access-token $$BUILDKITE_AGENT_ACCESS_TOKEN && tar -xzf build.tar.gz"
      - "./.cicd/tests.sh"
    env:
      IMAGE_TAG: "ubuntu-18.04"
    agents:
      queue: "automation-gke-ha-dev-taurus-tester-fleet"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_UBUNTU_18}${SKIP_LINUX}${SKIP_UNIT_TESTS}

  - label: ":ubuntu: Ubuntu 20.04 - Unit Tests"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':ubuntu: Ubuntu 20.04 - Build' --agent-access-token $$BUILDKITE_AGENT_ACCESS_TOKEN && tar -xzf build.tar.gz"
      - "./.cicd/tests.sh"
    env:
      IMAGE_TAG: "ubuntu-20.04"
    agents:
      queue: "automation-gke-ha-dev-taurus-tester-fleet"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_UBUNTU_20}${SKIP_LINUX}${SKIP_UNIT_TESTS}

  - label: ":darwin: macOS 10.15 - Unit Tests"
    command:
      - "git clone $OUR_PR_REPO taurus-cdt"
      - "cd taurus-cdt && if [[ $BUILDKITE_BRANCH =~ ^pull/[0-9]+/head: ]]; then git fetch -v --prune origin refs/pull/$(echo $BUILDKITE_BRANCH | cut -d/ -f2)/head; fi"
      - "cd taurus-cdt && git checkout -f $BUILDKITE_COMMIT && git submodule update --init --recursive"
      - "cd taurus-cdt && buildkite-agent artifact download build.tar.gz . --step ':darwin: macOS 10.15 - Build' && tar -xzf build.tar.gz"
      - "cd taurus-cdt && ./.cicd/tests.sh"
    plugins:
      - EOSIO/anka#v0.6.0:
          no-volume: true
          inherit-environment-vars: true
          vm-name: 10.15.5_6C_14G_80G
          vm-registry-tag: "clean::cicd::git-ssh::nas::brew::buildkite-agent::${MACOS_10_15_TAG}"
          always-pull: true
          debug: true
          wait-network: true
          pre-execute-sleep: 5
          pre-execute-ping-sleep: github.com
          failover-registries:
            - 'registry-1'
            - 'registry-2'
      - EOSIO/skip-checkout#v0.1.1:
          cd: ~
    agents:
      - "queue=mac-anka-node-fleet"
    timeout: ${TIMEOUT:-20}
    skip: ${SKIP_MACOS_10_15}${SKIP_MAC}${SKIP_UNIT_TESTS}

  - label: ":aws: Amazon_Linux 2 - Toolchain Tests"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':aws: Amazon_Linux 2 - Build' --agent-access-token $$BUILDKITE_AGENT_ACCESS_TOKEN && tar -xzf build.tar.gz"
      - "./.cicd/toolchain-tests.sh"
    env:
      IMAGE_TAG: "amazonlinux-2"
    agents:
      queue: "automation-gke-ha-dev-taurus-tester-fleet"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_AMAZON_LINUX_2}${SKIP_LINUX}${SKIP_TOOLCHAIN_TESTS}

  - label: ":centos: CentOS 7.7 - Toolchain Tests"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':centos: CentOS 7.7 - Build' --agent-access-token $$BUILDKITE_AGENT_ACCESS_TOKEN && tar -xzf build.tar.gz"
      - "./.cicd/toolchain-tests.sh"
    env: 
      IMAGE_TAG: "centos-7.7"
    agents:
      queue: "automation-gke-ha-dev-taurus-tester-fleet"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_CENTOS_7}${SKIP_LINUX}${SKIP_TOOLCHAIN_TESTS}

  - label: ":ubuntu: Ubuntu 18.04 - Toolchain Tests"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':ubuntu: Ubuntu 18.04 - Build' --agent-access-token $$BUILDKITE_AGENT_ACCESS_TOKEN && tar -xzf build.tar.gz"
      - "./.cicd/toolchain-tests.sh"
    env:
      IMAGE_TAG: "ubuntu-18.04"
    agents:
      queue: "automation-gke-ha-dev-taurus-tester-fleet"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_UBUNTU_18}${SKIP_LINUX}${SKIP_TOOLCHAIN_TESTS}

  - label: ":ubuntu: Ubuntu 20.04 - Toolchain Tests"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':ubuntu: Ubuntu 20.04 - Build' --agent-access-token $$BUILDKITE_AGENT_ACCESS_TOKEN && tar -xzf build.tar.gz"
      - "./.cicd/toolchain-tests.sh"
    env:
      IMAGE_TAG: "ubuntu-20.04"
    agents:
      queue: "automation-gke-ha-dev-taurus-tester-fleet"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_UBUNTU_20}${SKIP_LINUX}${SKIP_TOOLCHAIN_TESTS}

  - label: ":darwin: macOS 10.15 - Toolchain Tests"
    command:
      - "git clone $OUR_PR_REPO taurus-cdt"
      - "cd taurus-cdt && if [[ $BUILDKITE_BRANCH =~ ^pull/[0-9]+/head: ]]; then git fetch -v --prune origin refs/pull/$(echo $BUILDKITE_BRANCH | cut -d/ -f2)/head; fi"
      - "cd taurus-cdt && git checkout -f $BUILDKITE_COMMIT && git submodule update --init --recursive"
      - "cd taurus-cdt && buildkite-agent artifact download build.tar.gz . --step ':darwin: macOS 10.15 - Build' && tar -xzf build.tar.gz"
      - "cd taurus-cdt && ./.cicd/toolchain-tests.sh"
    plugins:
      - EOSIO/anka#v0.6.1:
          no-volume: true
          inherit-environment-vars: true
          vm-name: 10.15.5_6C_14G_80G
          vm-registry-tag: "clean::cicd::git-ssh::nas::brew::buildkite-agent::${MACOS_10_15_TAG}"
          always-pull: true
          debug: true
          wait-network: true
          pre-execute-sleep: 5
          pre-execute-ping-sleep: github.com
          failover-registries:
            - 'registry-1'
            - 'registry-2'
      - EOSIO/skip-checkout#v0.1.1:
          cd: ~
    agents:
      - "queue=mac-anka-node-fleet"
    timeout: ${TIMEOUT:-20}
    skip: ${SKIP_MACOS_10_15}${SKIP_MAC}${SKIP_TOOLCHAIN_TESTS}

  - label: ":ubuntu: Ubuntu 18.04 - Integration Tests"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':ubuntu: Ubuntu 18.04 - Build' --agent-access-token $$BUILDKITE_AGENT_ACCESS_TOKEN && tar -xzf build.tar.gz"
      - "./.cicd/integration-tests.sh"
    env:
      IMAGE_TAG: "ubuntu-18.04"
    agents:
      queue: "automation-gke-ha-dev-taurus-tester-fleet"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_UBUNTU_18}${SKIP_LINUX}${SKIP_INTEGRATION_TESTS}

  - wait:
    continue_on_failure: true

  - label: ":bar_chart: Unit Tests Metrics"
    command: |
      echo '+++ :compression: Extracting Unit Tests Metrics Code'
      tar -zxf .cicd/metrics/test-metrics.tar.gz
      echo '+++ :javascript: Running test-metrics.js'
      node --max-old-space-size=32768 test-metrics.js
    agents:
      queue: "automation-gke-ha-dev-taurus-tester-fleet"
    timeout: 10
    soft_fail: true

  - wait

  - label: ":centos: Centos 7.7 - Package Builder"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':centos: CentOS 7.7 - Build' --agent-access-token $$BUILDKITE_AGENT_ACCESS_TOKEN && tar -xzf build.tar.gz"
      - "./.cicd/package.sh"
    env:
      BUILDKITE_AGENT_ACCESS_TOKEN:
      IMAGE_TAG: "centos-7.7"
      OS: "el7" # OS and PKGTYPE required for lambdas
      PKGTYPE: "rpm"
    agents:
      queue: "automation-gke-ha-dev-taurus-tester-fleet"
    key: "centos7pb"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_CENTOS_7}${SKIP_LINUX}${SKIP_PACKAGE_BUILDER}

  - label: ":centos: Centos 7.7 - Test Package"
    command: |
      buildkite-agent artifact download '*.rpm' . --step ':centos: Centos 7.7 - Package Builder' --agent-access-token $$BUILDKITE_AGENT_ACCESS_TOKEN
      ./.cicd/test-package.sh
    env:
      IMAGE: "centos:7"
    agents:
      queue: "automation-gke-ha-dev-taurus-tester-fleet"
    depends_on: "centos7pb"
    allow_dependency_failure: false
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_CENTOS_7}${SKIP_LINUX}${SKIP_PACKAGE_BUILDER}${SKIP_PACKAGE_BUILDER_TEST}

  - label: ":ubuntu: Ubuntu 18.04 - Package Builder"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':ubuntu: Ubuntu 18.04 - Build' --agent-access-token $$BUILDKITE_AGENT_ACCESS_TOKEN && tar -xzf build.tar.gz"
      - "./.cicd/package.sh"
    env:
      BUILDKITE_AGENT_ACCESS_TOKEN:
      IMAGE_TAG: "ubuntu-18.04"
      OS: "ubuntu-18.04" # OS and PKGTYPE required for lambdas
      PKGTYPE: "deb"
    agents:
      queue: "automation-gke-ha-dev-taurus-tester-fleet"
    key: "ubuntu1804pb"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_UBUNTU_18}${SKIP_LINUX}${SKIP_PACKAGE_BUILDER}

  - label: ":ubuntu: Ubuntu 18.04 - Test Package"
    command: |
      buildkite-agent artifact download '*.deb' . --step ':ubuntu: Ubuntu 18.04 - Package Builder' --agent-access-token $$BUILDKITE_AGENT_ACCESS_TOKEN
      ./.cicd/test-package.sh
    env:
      IMAGE: "ubuntu:18.04"
    agents:
      queue: "automation-gke-ha-dev-taurus-tester-fleet"
    depends_on: "ubuntu1804pb"
    allow_dependency_failure: false
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_UBUNTU_18}${SKIP_LINUX}${SKIP_PACKAGE_BUILDER}${SKIP_PACKAGE_BUILDER_TEST}

  - label: ":ubuntu: Ubuntu 20.04 - Package Builder"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':ubuntu: Ubuntu 20.04 - Build' --agent-access-token $$BUILDKITE_AGENT_ACCESS_TOKEN && tar -xzf build.tar.gz"
      - "./.cicd/package.sh"
    env:
      BUILDKITE_AGENT_ACCESS_TOKEN:
      IMAGE_TAG: "ubuntu-20.04"
      OS: "ubuntu-20.04" # OS and PKGTYPE required for lambdas
      PKGTYPE: "deb"
    agents:
      queue: "automation-gke-ha-dev-taurus-tester-fleet"
    key: "ubuntu2004pb"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_UBUNTU_20}${SKIP_LINUX}${SKIP_PACKAGE_BUILDER}

  - label: ":ubuntu: Ubuntu 20.04 - Test Package"
    command: |
      buildkite-agent artifact download '*.deb' . --step ':ubuntu: Ubuntu 20.04 - Package Builder' --agent-access-token $$BUILDKITE_AGENT_ACCESS_TOKEN
      ./.cicd/test-package.sh
    env:
      IMAGE: "ubuntu:20.04"
    agents:
      queue: "automation-gke-ha-dev-taurus-tester-fleet"
    depends_on: "ubuntu2004pb"
    allow_dependency_failure: false
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_UBUNTU_20}${SKIP_LINUX}${SKIP_PACKAGE_BUILDER}${SKIP_PACKAGE_BUILDER_TEST}

  - label: ":darwin: macOS 10.15 - Package Builder"
    command:
      - "git clone $OUR_PR_REPO taurus-cdt"
      - "cd taurus-cdt && if [[ $BUILDKITE_BRANCH =~ ^pull/[0-9]+/head: ]]; then git fetch -v --prune origin refs/pull/$(echo $BUILDKITE_BRANCH | cut -d/ -f2)/head; fi"
      - "cd taurus-cdt && git checkout -f $BUILDKITE_COMMIT && git submodule update --init --recursive"
      - "cd taurus-cdt && buildkite-agent artifact download build.tar.gz . --step ':darwin: macOS 10.15 - Build' && tar -xzf build.tar.gz"
      - "cd taurus-cdt && ./.cicd/package.sh"
    plugins:
      - EOSIO/anka#v0.6.1:
          no-volume: true
          inherit-environment-vars: true
          vm-name: 10.15.5_6C_14G_80G
          vm-registry-tag: "clean::cicd::git-ssh::nas::brew::buildkite-agent::${MACOS_10_15_TAG}"
          always-pull: true
          debug: true
          wait-network: true
          pre-execute-sleep: 5
          pre-execute-ping-sleep: github.com
          failover-registries:
            - "registry-1"
            - "registry-2"
      - EOSIO/skip-checkout#v0.1.1:
          cd: ~
    agents:
      - "queue=mac-anka-node-fleet"
    key: "macos1015pb"
    timeout: ${TIMEOUT:-20}
    skip: ${SKIP_MACOS_10_15}${SKIP_MAC}${SKIP_PACKAGE_BUILDER}

  - label: ":darwin: macOS 10.15 - Test Package"
    command:
      - "git clone $BUILDKITE_REPO eosio.cdt && cd eosio.cdt && git checkout -f $BUILDKITE_COMMIT"
      - "cd eosio.cdt && buildkite-agent artifact download '*' . --step ':darwin: macOS 10.15 - Package Builder' --agent-access-token $$BUILDKITE_AGENT_ACCESS_TOKEN"
      - "cd eosio.cdt && ./.cicd/test-package.anka.sh"
    plugins:
      - EOSIO/anka#v0.6.1:
          no-volume: true
          inherit-environment-vars: true
          vm-name: 10.15.5_6C_14G_80G
          vm-registry-tag: "clean::cicd::git-ssh::nas::brew::buildkite-agent"
          always-pull: true
          debug: true
          wait-network: true
          pre-execute-sleep: 5
          pre-execute-ping-sleep: github.com
          failover-registries:
            - 'registry_1'
            - 'registry_2'
      - EOSIO/skip-checkout#v0.1.1:
          cd: ~
    agents:
      - "queue=mac-anka-node-fleet"
    depends_on: "macos1015pb"
    allow_dependency_failure: false
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_MACOS_10_15}${SKIP_PACKAGE_BUILDER}${SKIP_MAC}${SKIP_PACKAGE_BUILDER_TEST}

  - wait

  - label: ":docker::ubuntu: Docker - Build 18.04 Docker Image"
    command: "./.cicd/create-docker-from-binary.sh"
    agents:
      queue: "automation-gke-ha-dev-taurus-tester-fleet"
    skip: ${SKIP_UBUNTU_20}${SKIP_LINUX}${SKIP_PACKAGE_BUILDER}
    timeout: 10

  - label: ":beer: Brew Updater"
    command: |
      buildkite-agent artifact download eosio.cdt.rb . --step ':darwin: macOS 10.15 - Package Builder'
      mv eosio.cdt.rb eosio_cdt_catalina.rb
      buildkite-agent artifact upload eosio_cdt_catalina.rb
    agents:
      queue: "automation-gke-ha-dev-basic-builder-fleet"
    timeout: "${TIMEOUT:-5}"
    skip: ${SKIP_MACOS_10_15}${SKIP_MAC}${SKIP_PACKAGE_BUILDER}

  - label: ":git: Git Submodule Regression Check"
    command:
      - "./.cicd/submodule-regression-checker.sh"
    agents:
      queue: "automation-gke-ha-dev-basic-builder-fleet"
    timeout: 5
