steps:
  - wait

  - label: ":aws: Amazon_Linux 2 - Build"
    command:
      - "./.cicd/build.sh"
      - "tar -pczf build.tar.gz build && buildkite-agent artifact upload build.tar.gz"
    env:
      IMAGE_TAG: "amazonlinux-2"
    agents:
      queue: "automation-eks-eos-builder-fleet"
    timeout: ${TIMEOUT:-60}
    skip: $SKIP_AMAZON_LINUX_2

  - label: ":centos: CentOS 7.7 - Build"
    command:
      - "./.cicd/build.sh"
      - "tar -pczf build.tar.gz build && buildkite-agent artifact upload build.tar.gz"
    env: 
      IMAGE_TAG: "centos-7.7"
    agents:
      queue: "automation-eks-eos-builder-fleet"
    timeout: ${TIMEOUT:-60}
    skip: $SKIP_CENTOS_7

  - label: ":centos: CentOS 8 - Build"
    command:
      - "./.cicd/build.sh"
      - "tar -pczf build.tar.gz build && buildkite-agent artifact upload build.tar.gz"
    env: 
      IMAGE_TAG: "centos-8"
    agents:
      queue: "automation-eks-eos-builder-fleet"
    timeout: ${TIMEOUT:-60}
    skip: $SKIP_CENTOS_8

  - label: ":ubuntu: Ubuntu 16.04 - Build"
    command:
      - "./.cicd/build.sh"
      - "tar -pczf build.tar.gz build && buildkite-agent artifact upload build.tar.gz"
    env: 
      IMAGE_TAG: "ubuntu-16.04"
    agents:
      queue: "automation-eks-eos-builder-fleet"
    timeout: ${TIMEOUT:-60}
    skip: $SKIP_UBUNTU_16

  - label: ":ubuntu: Ubuntu 18.04 - Build"
    command:
      - "./.cicd/build.sh"
      - "tar -pczf build.tar.gz build && buildkite-agent artifact upload build.tar.gz"
    env:
      IMAGE_TAG: "ubuntu-18.04"
    agents:
      queue: "automation-eks-eos-builder-fleet"
    timeout: ${TIMEOUT:-60}
    skip: $SKIP_UBUNTU_18

  - label: ":ubuntu: Ubuntu 20.04 - Build"
    command:
      - "./.cicd/build.sh"
      - "tar -pczf build.tar.gz build && buildkite-agent artifact upload build.tar.gz"
    env:
      IMAGE_TAG: "ubuntu-20.04"
    agents:
      queue: "automation-eks-eos-builder-fleet"
    timeout: ${TIMEOUT:-60}
    skip: $SKIP_UBUNTU_20

  - label: ":darwin: macOS 10.14 - Build"
    command:
      - "git clone $BUILDKITE_REPO eosio.cdt"
      - "cd eosio.cdt && if [[ $BUILDKITE_BRANCH =~ ^pull/[0-9]+/head: ]]; then git fetch -v --prune origin refs/pull/$(echo $BUILDKITE_BRANCH | cut -d/ -f2)/head; fi"
      - "cd eosio.cdt && git checkout -f $BUILDKITE_COMMIT && git submodule update --init --recursive"
      - "cd eosio.cdt && ./.cicd/build.sh"
      - "cd eosio.cdt && tar -pczf build.tar.gz build && buildkite-agent artifact upload build.tar.gz"
    plugins:
      - EOSIO/anka#v0.6.1:
          no-volume: true
          inherit-environment-vars: true
          vm-name: 10.14.6_6C_14G_80G
          vm-registry-tag: "clean::cicd::git-ssh::nas::brew::buildkite-agent::${MACOS_10_14_FILE_HASH}"
          modify-cpu: 12
          modify-ram: 24
          always-pull: true
          debug: true
          wait-network: true
          pre-execute-sleep: 5
          pre-execute-ping-sleep: github.com
          failover-registries:
            - 'registry-1'
            - 'registry-2'
          pre-commands:
            - "rm -rf mac-anka-fleet; git clone git@github.com/EOSIO/mac-anka-fleet.git && cd mac-anka-fleet && . ./ensure-tag.bash -u 12 -r 25G -a '-n'"
      - EOSIO/skip-checkout#v0.1.1:
          cd: ~
    env:
      PROJECT_TAG: ${MACOS_10_14_FILE_HASH}
      REPO: ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO}
      REPO_COMMIT: $BUILDKITE_COMMIT
      TAG_COMMANDS: "git clone ${BUILDKITE_PULL_REQUEST_REPO:-$BUILDKITE_REPO} eosio.cdt && cd eosio.cdt && git checkout -f \$BUILDKITE_COMMIT && git submodule update --init --recursive && . ./.cicd/docker/macos-10.14.sh && cd ~/eosio.cdt && cd .. && rm -rf eosio.cdt"
      TEMPLATE: 10.14.6_6C_14G_80G
      TEMPLATE_TAG: clean::cicd::git-ssh::nas::brew::buildkite-agent
    timeout: ${TIMEOUT:-120}
    agents:
      - "queue=mac-anka-large-node-fleet"
    skip: $SKIP_MOJAVE

  - wait

  - label: ":aws: Amazon_Linux 2 - Unit Tests"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':aws: Amazon_Linux 2 - Build' --agent-access-token $$BUILDKITE_AGENT_ACCESS_TOKEN && tar -xzf build.tar.gz"
      - "./.cicd/tests.sh"
    env:
      IMAGE_TAG: "amazonlinux-2"
    agents:
      queue: "automation-eks-eos-tester-fleet"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_AMAZON_LINUX_2}${SKIP_UNIT_TESTS}

  - label: ":centos: CentOS 7.7 - Unit Tests"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':centos: CentOS 7.7 - Build' --agent-access-token $$BUILDKITE_AGENT_ACCESS_TOKEN && tar -xzf build.tar.gz"
      - "./.cicd/tests.sh"
    env: 
      IMAGE_TAG: "centos-7.7"
    agents:
      queue: "automation-eks-eos-tester-fleet"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_CENTOS_7}${SKIP_UNIT_TESTS}

  - label: ":centos: CentOS 8 - Unit Tests"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':centos: CentOS 8 - Build' --agent-access-token $$BUILDKITE_AGENT_ACCESS_TOKEN && tar -xzf build.tar.gz"
      - "./.cicd/tests.sh"
    env: 
      IMAGE_TAG: "centos-8"
    agents:
      queue: "automation-eks-eos-tester-fleet"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_CENTOS_8}${SKIP_UNIT_TESTS}

  - label: ":ubuntu: Ubuntu 16.04 - Unit Tests"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':ubuntu: Ubuntu 16.04 - Build' --agent-access-token $$BUILDKITE_AGENT_ACCESS_TOKEN && tar -xzf build.tar.gz"
      - "./.cicd/tests.sh"
    env: 
      IMAGE_TAG: "ubuntu-16.04"
    agents:
      queue: "automation-eks-eos-tester-fleet"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_UBUNTU_16}${SKIP_UNIT_TESTS}

  - label: ":ubuntu: Ubuntu 18.04 - Unit Tests"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':ubuntu: Ubuntu 18.04 - Build' --agent-access-token $$BUILDKITE_AGENT_ACCESS_TOKEN && tar -xzf build.tar.gz"
      - "./.cicd/tests.sh"
    env:
      IMAGE_TAG: "ubuntu-18.04"
    agents:
      queue: "automation-eks-eos-tester-fleet"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_UBUNTU_18}${SKIP_UNIT_TESTS}

  - label: ":ubuntu: Ubuntu 20.04 - Unit Tests"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':ubuntu: Ubuntu 20.04 - Build' --agent-access-token $$BUILDKITE_AGENT_ACCESS_TOKEN && tar -xzf build.tar.gz"
      - "./.cicd/tests.sh"
    env:
      IMAGE_TAG: "ubuntu-20.04"
    agents:
      queue: "automation-eks-eos-tester-fleet"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_UBUNTU_20}${SKIP_UNIT_TESTS}

  - label: ":darwin: macOS 10.14 - Unit Tests"
    command:
      - "git clone $BUILDKITE_REPO eosio.cdt"
      - "cd eosio.cdt && if [[ $BUILDKITE_BRANCH =~ ^pull/[0-9]+/head: ]]; then git fetch -v --prune origin refs/pull/$(echo $BUILDKITE_BRANCH | cut -d/ -f2)/head; fi"
      - "cd eosio.cdt && git checkout -f $BUILDKITE_COMMIT && git submodule update --init --recursive"
      - "cd eosio.cdt && buildkite-agent artifact download build.tar.gz . --step ':darwin: macOS 10.14 - Build' && tar -xzf build.tar.gz"
      - "cd eosio.cdt && ./.cicd/tests.sh"
    plugins:
      - EOSIO/anka#v0.6.1:
          no-volume: true
          inherit-environment-vars: true
          vm-name: 10.14.6_6C_14G_80G
          vm-registry-tag: "clean::cicd::git-ssh::nas::brew::buildkite-agent"
          always-pull: true
          debug: true
          wait-network: true
          pre-execute-sleep: 5
          pre-execute-ping-sleep: github.com
          failover-registries:
            - 'registry-1'
            - 'registry-2'
      - EOSIO/skip-checkout#v0.1.1:
          cd: ~
    agents:
      - "queue=mac-anka-node-fleet"
    skip: ${SKIP_MOJAVE}${SKIP_UNIT_TESTS}

  - wait:
    continue_on_failure: true

  - label: ":bar_chart: Unit Tests Metrics"
    command: |
      echo '+++ :compression: Extracting Unit Tests Metrics Code'
      tar -zxf .cicd/metrics/test-metrics.tar.gz
      echo '+++ :javascript: Running test-metrics.js'
      node --max-old-space-size=32768 test-metrics.js
    agents:
      queue: "automation-eks-eos-tester-fleet"
    timeout: 10
    soft_fail: true

  - wait

  - label: ":aws: Amazon_Linux 2 - Package Builder"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':aws: Amazon_Linux 2 - Build' --agent-access-token $$BUILDKITE_AGENT_ACCESS_TOKEN && tar -xzf build.tar.gz"
      - "./.cicd/package.sh"
    env:
      BUILDKITE_AGENT_ACCESS_TOKEN:
      IMAGE_TAG: "amazonlinux-2"
      OS: "amzn" # OS and PKGTYPE required for lambdas
      PKGTYPE: "rpm"
    agents:
      queue: "automation-eks-eos-tester-fleet"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_AMAZON_LINUX_2}${SKIP_PACKAGE_BUILDER}

  - label: ":centos: Centos 7.7 - Package Builder"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':centos: CentOS 7.7 - Build' --agent-access-token $$BUILDKITE_AGENT_ACCESS_TOKEN && tar -xzf build.tar.gz"
      - "./.cicd/package.sh"
    env:
      BUILDKITE_AGENT_ACCESS_TOKEN:
      IMAGE_TAG: "centos-7.7"
      OS: "centos" # OS and PKGTYPE required for lambdas
      PKGTYPE: "rpm"
    agents:
      queue: "automation-eks-eos-tester-fleet"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_CENTOS_7}${SKIP_PACKAGE_BUILDER}

  - label: ":centos: Centos 8 - Package Builder"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':centos: CentOS 8 - Build' --agent-access-token $$BUILDKITE_AGENT_ACCESS_TOKEN && tar -xzf build.tar.gz"
      - "./.cicd/package.sh"
    env:
      BUILDKITE_AGENT_ACCESS_TOKEN:
      IMAGE_TAG: "centos-8"
      OS: "centos" # OS and PKGTYPE required for lambdas
      PKGTYPE: "rpm"
    agents:
      queue: "automation-eks-eos-tester-fleet"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_CENTOS_8}${SKIP_PACKAGE_BUILDER}

  - label: ":ubuntu: Ubuntu 16.04 - Package Builder"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':ubuntu: Ubuntu 16.04 - Build' --agent-access-token $$BUILDKITE_AGENT_ACCESS_TOKEN && tar -xzf build.tar.gz"
      - "./.cicd/package.sh"
    env:
      BUILDKITE_AGENT_ACCESS_TOKEN:
      IMAGE_TAG: "ubuntu-16.04"
      OS: "ubuntu-16.04" # OS and PKGTYPE required for lambdas
      PKGTYPE: "deb"
    agents:
      queue: "automation-eks-eos-tester-fleet"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_UBUNTU_16}${SKIP_PACKAGE_BUILDER}

  - label: ":ubuntu: Ubuntu 18.04 - Package Builder"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':ubuntu: Ubuntu 18.04 - Build' --agent-access-token $$BUILDKITE_AGENT_ACCESS_TOKEN && tar -xzf build.tar.gz"
      - "./.cicd/package.sh"
    env:
      BUILDKITE_AGENT_ACCESS_TOKEN:
      IMAGE_TAG: "ubuntu-18.04"
      OS: "ubuntu-18.04" # OS and PKGTYPE required for lambdas
      PKGTYPE: "deb"
    agents:
      queue: "automation-eks-eos-tester-fleet"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_UBUNTU_18}${SKIP_PACKAGE_BUILDER}

  - label: ":ubuntu: Ubuntu 20.04 - Package Builder"
    command:
      - "buildkite-agent artifact download build.tar.gz . --step ':ubuntu: Ubuntu 20.04 - Build' --agent-access-token $$BUILDKITE_AGENT_ACCESS_TOKEN && tar -xzf build.tar.gz"
      - "./.cicd/package.sh"
    env:
      BUILDKITE_AGENT_ACCESS_TOKEN:
      IMAGE_TAG: "ubuntu-20.04"
      OS: "ubuntu-20.04" # OS and PKGTYPE required for lambdas
      PKGTYPE: "deb"
    agents:
      queue: "automation-eks-eos-tester-fleet"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_UBUNTU_20}${SKIP_PACKAGE_BUILDER}

  - label: ":darwin: Mojave - Package Builder"
    command:
      - "git clone $BUILDKITE_REPO eosio.cdt"
      - "cd eosio.cdt && if [[ $BUILDKITE_BRANCH =~ ^pull/[0-9]+/head: ]]; then git fetch -v --prune origin refs/pull/$(echo $BUILDKITE_BRANCH | cut -d/ -f2)/head; fi"
      - "cd eosio.cdt && git checkout -f $BUILDKITE_COMMIT && git submodule update --init --recursive"
      - "cd eosio.cdt && buildkite-agent artifact download build.tar.gz . --step ':darwin: macOS 10.14 - Build' && tar -xzf build.tar.gz"
      - "cd eosio.cdt && ./.cicd/package.sh"
    plugins:
      - EOSIO/anka#v0.6.1:
          no-volume: true
          inherit-environment-vars: true
          vm-name: 10.14.6_6C_14G_80G
          vm-registry-tag: "clean::cicd::git-ssh::nas::brew::buildkite-agent"
          always-pull: true
          debug: true
          wait-network: true
          pre-execute-sleep: 5
          pre-execute-ping-sleep: github.com
          failover-registries:
            - 'registry-1'
            - 'registry-2'
      - EOSIO/skip-checkout#v0.1.1:
          cd: ~
    agents:
      - "queue=mac-anka-node-fleet"
    timeout: ${TIMEOUT:-10}
    skip: ${SKIP_MOJAVE}${SKIP_PACKAGE_BUILDER}

  - wait
  
  - label: ":docker::ubuntu: Docker - Build 18.04 Docker Image"
    command: "./.cicd/create-docker-from-binary.sh"
    agents:
      queue: "automation-eks-eos-tester-fleet"
    timeout: 10

  - label: ":beer: Brew Updater"
    command: |
      buildkite-agent artifact download eosio.cdt.rb . --step ':darwin: Mojave - Package Builder'
      mv eosio.cdt.rb eosio_cdt_mojave.rb
      buildkite-agent artifact upload eosio_cdt_mojave.rb
    agents:
      queue: "automation-basic-builder-fleet"
    timeout: "${TIMEOUT:-5}"
    skip: ${SKIP_MOJAVE}${SKIP_PACKAGE_BUILDER}

  - label: ":git: Git Submodule Regression Check"
    command:
      - "./.cicd/submodule-regression-checker.sh"
    agents:
      queue: "automation-basic-builder-fleet"
    timeout: 5
