env:
  BUILD_TIMEOUT: 120
  TEST_TIMEOUT: 60
  TIMEOUT: 120
  VERBOSE: true

steps:

  - label: ":webhook: Trigger Travis CI Build"
    command:
      - "./.cicd/travis-trigger.sh"
    agents:
      queue: "automation-eos-builder-fleet"

  - trigger: "eosio-dot-cdt-base-images-beta"
    label: ":docker: Ensure base images exist"
    build:
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"

  - wait

  - label: ":aws: [Amazon] 2 Build"
    agents:
      queue: "automation-eos-builder-fleet"
    plugins:
      - docker#v3.2.0:
          debug: $DEBUG
          image: "eosio/producer:eosio.cdt-amazonlinux-2-ea0e784ba06b4e0c64b7ba808dbe1898ddcc958c"
          environment:
            - "MAKE_PROC_LIMIT"
    timeout: $BUILD_TIMEOUT
    skip: $SKIP_AMAZON_LINUX_2

  - label: ":centos: [CentOS] 7 Build"
    agents:
      queue: "automation-eos-builder-fleet"
    plugins:
      - docker#v3.2.0:
          debug: $DEBUG
          image: "eosio/producer:eosio.cdt-centos-7-297228b12eb9cbeab202a1ab3de0ce192dd46741"
          environment:
            - "MAKE_PROC_LIMIT"
    timeout: $BUILD_TIMEOUT
    skip: $SKIP_CENTOS_7

  - label: ":ubuntu: [Ubuntu] 16.04 Build"
    agents:
      queue: "automation-eos-builder-fleet"
    plugins:
      - docker#v3.2.0:
          debug: $DEBUG
          image: "eosio/producer:eosio.cdt-ubuntu-16.04-320d7b3ec428c13a058dfd1957d4629b32080478"
          environment:
            - "MAKE_PROC_LIMIT"
    timeout: $BUILD_TIMEOUT
    skip: $SKIP_UBUNTU_16

  - label: ":ubuntu: [Ubuntu] 18.04 Build"
    agents:
      queue: "automation-eos-builder-fleet"
    plugins:
      - docker#v3.2.0:
          debug: $DEBUG
          image: "eosio/producer:eosio.cdt-ubuntu-18.04-473afea250c03d0bbd6352bf3f4ee5277f2935eb"
          environment:
            - "MAKE_PROC_LIMIT"
    timeout: $BUILD_TIMEOUT
    skip: $SKIP_UBUNTU_18

  - label: ":darwin: [Darwin] 10.14 Build"
    command:
      - "brew install git automake libtool wget cmake gmp gettext doxygen graphviz lcov python@3"
      - "git clone $BUILDKITE_REPO eosio.cdt && cd eosio.cdt && git checkout $BUILDKITE_COMMIT && git submodule update --init --recursive"
      - "cd eosio.cdt && mkdir build && cd build && cmake .. && make -j$(getconf _NPROCESSORS_ONLN)"
      - "cd eosio.cdt/build && ctest -j$(getconf _NPROCESSORS_ONLN) -L unit_tests -V -T Test"
    plugins:
      - chef/anka#v0.5.1:
          no-volume: true
          inherit-environment-vars: true
          vm-name: 10.14.4_6C_14G_40G
          vm-registry-tag: "clean::cicd::git-ssh::nas::brew"
          modify-cpu: 12
          modify-ram: 24
          always-pull: true
          debug: true
          wait-network: true
    agents:
      - "queue=mac-anka-large-node-fleet"
    timeout: $BUILD_TIMEOUT
    skip: $SKIP_MOJAVE