language: c
before_install:
  - eval "${MATRIX_EVAL}"
  - scripts/travis-before-install.sh
script:
  - scripts/travis-build.sh
  - scripts/travis-test.sh
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc-i686
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
      env: WABT_DEPLOY=clang-release
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
      env: SANITIZER=asan
# Disabled because MSAN seems to have stopped working on Travis.
#    - os: linux
#      dist: trusty
#      sudo: required
#      compiler: clang
#      env: SANITIZER=msan
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
      env: SANITIZER=lsan
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
      env: SANITIZER=ubsan
    - os: osx
      compiler: clang
      env: WABT_DEPLOY=clang-release
    # Build the .js outputs using emcc
    - &test-emcc
      stage: test
      compiler: clang
      python: 2.7
      node_js: 7
      language: node_js
      node_js:
      - node
      sudo: required
      services:
      - docker
      before_install:
      - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit bash
      script:
      # run binaryen.js and wasm.js tests before and after building, so we see if the bundled
      # version is good too
      - docker exec -it emscripten bash scripts/travis-emcc.sh

  # Allow failures on the Mac bots. We'd rather not, but they are quite slow.
  allow_failures:
    - os: osx
      compiler: clang

  fast_finish: true

before_deploy:
  # Only run deploy script once (see https://github.com/travis-ci/travis-ci/issues/2570#issuecomment-171262181)
  - >
    if ! [ "$BEFORE_DEPLOY_RUN" ]; then
      export BEFORE_DEPLOY_RUN=1;
      scripts/travis-before-deploy.sh
    fi

deploy:
  - provider: releases
    api_key:
      secure: UTs36nT7zk1E5cmv4PmsrLbfpQoCJmkQ1upBvyiUl7F2GtPpd7bn/lxN9+e6xroW3vvFTD0MAx/ylqqKHISMhUlRj3vSRW9M1JO/EKj3jQ8kqr92Nz9On5QcGJ8usMMuzq4rXW/t32XIFci25RlFTBxAVXaQq6cVbvjGzvGfvJ6V6vTtho6Pjgj2HCq3K38TYMwA6/+NiP30bV2OkYKjTRx6RCFkYUhKallr0t035GT30bgW7Zz5roLlXUXMiCt8TqY5MCcFYmKukYpLF/tp+B5MUXR0rFFoTsafOc7hWCIi9SdngkwlUFW2tbc9CD0MtNEIUpF+Pf+siXo2RKqfg9A4pdHyHTx1PIOqyDTGcMLHBrs8bsQAoO4PJy6V0WLA1PwQDajXzGfFC3O7Wg/ljOpUumaHCt8yl3/aFu0LZu1NOCZnTpu/kLMXiB1osbSPuYqO+v2j8qgS6xDWf183d9cBzqlep+Wnk2Pgoq1PX2lO08QfxJjW6o3dJkZ/4icpT8hHb4ymcIr3VI9Pl+5Gg1JiMZooZeGV/XMXDAaaO2SNELOK4Dz9eBy4d4ffgaNPZkmNIJZLEx8nISDCU+u2VLcC5FHsCT8VyjcG9JdAXwOmlv2auxhyU87buteJvsJFDavfnc4BEgHPM1xR9PVJzY3IXAOAwAXUZQPWxSKwEgQ=
    file: wabt-$TRAVIS_TAG-*.tar.gz*
    file_glob: true
    skip_cleanup: true
    on:
      tags: true
      condition: -n ${WABT_DEPLOY}
  - provider: gcs
    access_key_id: GOOGF5TNXVUMCZBNQSHP54QW
    secret_access_key:
      secure: s4RCOYQnJNj/9cwdsKf7nz3K232Ffc2eAetfItCYuVIFSSvPKrMAsvDBfyG6drINWKDwBN1qJj7P0jj9xYZ1lish291kh8UkecaHzUKufq8vRTB4sVqoTNFUwfuKTnnVn+M+R7d42b4nMbC9dddKwYqWZaBv6pqt1N431hsMoK0sWzfEQFZldvp42TgMBGI1RATaKwW8t2SfYtk/y8/gLAbaVOGW2MRkGulU3ZbjTTGMqO5P+3iWtRNHcdLh9rvxI5T31vjwj4FdymGkza7daQqMuXdDDh9kURuMtbcIGnO/9Wr/EWG4r0BJ8nMkUVm4pVN15V1AaBTpQI3RmorERpPOMu6qbQI0zw3v6lb6xRIbeunDl9LvHR3YbORicsqnbMaNBnOpKumMojBb4KvEwawCd1RXhArfElgfpdO8J0Nk7VgKGoTN0yxIvivUxBY+5NO8v7M3kF7tOH5VpDmaQmaFyGxFZJTTnyVB+ukP/cfMF4WJWwDlnec+mMzLWSWlXEu+Ra96Qd19GEsyBeW+fNckeyGS1wBRowetpJRP2cS97V+owhOdvqVzXuZnD7/fPEtEgZ8DubCDnsuQM2JPFFoa26C1XmY/NRUssrSNuaJeTI/SRNUd14QBBMrjR9LVVyZnRtLsSgmzAVA2Sa/cvc2+RiweTCJeXst6zAYNEGU=
    bucket: webassembly
    skip_cleanup: true
    on:
      tags: true
      condition: -n ${WABT_DEPLOY}
    acl: public-read
    local_dir: gcs
